FROM node:20.12.0-alpine3.19

# Declare build arguments
ARG PORT
ARG NODE_ENV
ARG CLIENTSIDE_URL
ARG SUBMISSIONSERVICE_URL
ARG ATLAS_DB_URL
ARG LOG_DB_URL
ARG COSMOS_ENDPOINT
ARG COSMOS_KEY
ARG COSMOS_DBID
ARG COSMOS_CONTAINERID
ARG JWT_SECRET

WORKDIR /usr/app/

COPY package.json package-lock.json ./

COPY src ./src

RUN npm ci

CMD ["npm", "run", "dev"]