FROM node:20.12.0-alpine3.19

# Declare build arguments
ARG PORT
ARG NODE_ENV
ARG CLIENTSIDE_URL
ARG SUBMISSIONSERVICE_URL
ARG ATLAS_DB_URL
ARG LOG_DB_URL
ARG COSMOS_ENDPOINT
ARG COSMOS_KEY
ARG COSMOS_DBID
ARG COSMOS_CONTAINERID
ARG JWT_SECRET

WORKDIR /usr/app/

COPY package.json package-lock.json ./

COPY src ./src

RUN npm ci

# Set environment variables for the running container
ENV PORT=$PORT
ENV NODE_ENV=$NODE_ENV
ENV CLIENTSIDE_URL=$CLIENTSIDE_URL
ENV SUBMISSIONSERVICE_URL=$SUBMISSIONSERVICE_URL
ENV ATLAS_DB_URL=$ATLAS_DB_URL
ENV LOG_DB_URL=$LOG_DB_URL
ENV COSMOS_ENDPOINT=$COSMOS_ENDPOINT
ENV COSMOS_KEY=$COSMOS_KEY
ENV COSMOS_DBID=$COSMOS_DBID
ENV COSMOS_CONTAINERID=$COSMOS_CONTAINERID
ENV JWT_SECRET=$JWT_SECRET

CMD ["npm", "run", "dev"]